### ISSUE TITLE
[Bug] CUSTOMROM Sony AOSP GCAM crash

### ISSUE THREAD

**Issue by MartinX3** [MartinX3-AndroidDevelopment/bug_tracker#11]
**Platform:** TAMA
**Device:** AKARI, APOLLO, AURORA, AKATSUKI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Crash if we open a GCAM.

**Symptoms**
Crash.

**How to reproduce**
Open the GCAM.
[SonyAOSP_20__April_2019_gcam_crash_GC6_2-F1-v3.log](https://github.com/MartinX3sAndroidDevelopment/bug_tracker/files/3113805/SonyAOSP_20__April_2019_gcam_crash_GC6_2-F1-v3.log)

**Comment by MartinX3** [comment]
```
05-31 18:20:04.079  1037  2067 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.google.android.GoogleCamera/com.android.camera.CameraLauncher bnds=[789,1197][1038,1564]} from uid 10021
05-31 18:20:04.089   690  2487 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)
05-31 18:20:04.089   690  2487 D audio_route: Apply path: speaker
05-31 18:20:04.092   706   706 I RQBalance-PowerHAL-Hints: Setting performance mode
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 124, path = 0, app id = 0x11130, sample rate = 48000
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> send_asm_topology
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> send_adm_topology
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> send_audtable
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> send_audvoltable
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_VOL_STEP_TABLE_SIZE
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> AUDIO_SET_VOL_CAL cal type = 12
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_SIZE
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> send_audstrmtable
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> audstrm_cal->cal_type.cal_data.cal_size = 40
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> send_afe_topology
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 124, Topology Id 1025d
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> send_afe_cal
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE_SIZE
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 124 path = 0
05-31 18:20:04.134   690  2487 D ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
05-31 18:20:04.134   690  2487 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback
05-31 18:20:04.134   690  2487 D audio_route: Apply path: low-latency-playback
05-31 18:20:04.145  1037  1064 I ActivityManager: Start proc 4524:com.google.android.GoogleCamera/u0a68 for activity com.google.android.GoogleCamera/com.android.camera.CameraLauncher
05-31 18:20:04.173  4524  4524 W CAM_SearchIndexProv: Called onCreate
05-31 18:20:04.179  4524  4524 I CAM_Timing: CameraApp: START -> APP_ONCREATE_START: 6ms
05-31 18:20:04.180  1037  2067 W ActivityManager: Permission Denial: opening provider com.google.android.gsf.gservices.GservicesProvider from ProcessRecord{45fa785 4524:com.google.android.GoogleCamera/u0a68} (pid=4524, uid=10068) requires com.google.android.providers.gsf.permission.READ_GSERVICES or com.google.android.providers.gsf.permission.WRITE_GSERVICES
05-31 18:20:04.180  4524  4524 D AndroidRuntime: Shutting down VM
05-31 18:20:04.180  4524  4524 E AndroidRuntime: FATAL EXCEPTION: main
05-31 18:20:04.180  4524  4524 E AndroidRuntime: Process: com.google.android.GoogleCamera, PID: 4524
05-31 18:20:04.180  4524  4524 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.google.android.apps.camera.legacy.app.app.CameraApp: java.lang.SecurityException: Permission Denial: opening provider com.google.android.gsf.gservices.GservicesProvider from ProcessRecord{45fa785 4524:com.google.android.GoogleCamera/u0a68} (pid=4524, uid=10068) requires com.google.android.providers.gsf.permission.READ_GSERVICES or com.google.android.providers.gsf.permission.WRITE_GSERVICES
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: opening provider com.google.android.gsf.gservices.GservicesProvider from ProcessRecord{45fa785 4524:com.google.android.GoogleCamera/u0a68} (pid=4524, uid=10068) requires com.google.android.providers.gsf.permission.READ_GSERVICES or com.google.android.providers.gsf.permission.WRITE_GSERVICES
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1950)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1918)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1868)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:779)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1973)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1962)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at lhq.a(Unknown Source:34)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at lhq.b(Unknown Source:3)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at lhq.a(Unknown Source:0)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at com.google.android.apps.camera.legacy.app.app.CameraApp.onCreate(Unknown Source:24)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5920)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	... 8 more
05-31 18:20:04.180  4524  4524 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at com.android.server.content.ContentService.registerContentObserver(ContentService.java:340)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.content.IContentService$Stub.onTransact(IContentService.java:76)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at com.android.server.content.ContentService.onTransact(ContentService.java:262)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:731)
05-31 18:20:04.180  4524  4524 E AndroidRuntime: 
05-31 18:20:04.183  1037  2067 W ActivityManager:   Force finishing activity com.google.android.GoogleCamera/com.android.camera.CameraLauncher
05-31 18:20:04.186  1037  1063 I ActivityManager: Showing crash dialog for package com.google.android.GoogleCamera u0
05-31 18:20:04.195  1037  1062 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
05-31 18:20:04.195  1037  1062 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
05-31 18:20:04.202   690  2487 E msm8974_platform: ramp_speaker_gain: Could not get ctl for mixer cmd - Left Speaker Gain or Right Speaker Gain, not applying speaker gain ramp
05-31 18:20:04.203   690  2487 D audio_hw_primary: out_write: retry previous failed cal level set
05-31 18:20:04.299  1826  1851 E droid.launcher: No package ID ff found for ID 0xffffffff.
05-31 18:20:04.300  1826  1851 E IconLoader: Could not find icon drawable from resource
05-31 18:20:04.300  1826  1851 E IconLoader: android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
05-31 18:20:04.300  1826  1851 E IconLoader: 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
05-31 18:20:04.300  1826  1851 E IconLoader: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
05-31 18:20:04.300  1826  1851 E IconLoader: 	at android.content.res.Resources.getDrawable(Resources.java:827)
05-31 18:20:04.300  1826  1851 E IconLoader: 	at com.android.systemui.shared.recents.model.IconLoader.createNewIconForTask(IconLoader.java:118)
05-31 18:20:04.300  1826  1851 E IconLoader: 	at com.android.systemui.shared.recents.model.IconLoader.getAndInvalidateIfModified(IconLoader.java:94)
05-31 18:20:04.300  1826  1851 E IconLoader: 	at com.android.systemui.shared.recents.model.RecentsTaskLoader.getAndUpdateActivityIcon(RecentsTaskLoader.java:325)
05-31 18:20:04.300  1826  1851 E IconLoader: 	at com.android.systemui.shared.recents.model.RecentsTaskLoadPlan.executePlan(RecentsTaskLoadPlan.java:188)
05-31 18:20:04.300  1826  1851 E IconLoader: 	at com.android.systemui.shared.recents.model.RecentsTaskLoader.loadTasks(RecentsTaskLoader.java:173)
05-31 18:20:04.300  1826  1851 E IconLoader: 	at com.android.quickstep.RecentsModel.onTaskStackChangedBackground(RecentsModel.java:214)
05-31 18:20:04.300  1826  1851 E IconLoader: 	at com.android.systemui.shared.system.TaskStackChangeListeners.onTaskStackChanged(TaskStackChangeListeners.java:80)
05-31 18:20:04.300  1826  1851 E IconLoader: 	at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:50)
05-31 18:20:04.300  1826  1851 E IconLoader: 	at android.os.Binder.execTransact(Binder.java:731)
05-31 18:20:04.404   714  1021 W SurfaceFlinger: Attempting to set client state on removed layer: Surface(name=25b4c65 Application Error: com.google.android.GoogleCamera)/@0xb985419 - animation-leash#0
05-31 18:20:04.405   714  1021 W SurfaceFlinger: Attempting to destroy on removed layer: Surface(name=25b4c65 Application Error: com.google.android.GoogleCamera)/@0xb985419 - animation-leash#0
05-31 18:20:04.684  1037  1062 W ActivityManager: Activity pause timeout for ActivityRecord{91da21e u0 com.google.android.GoogleCamera/com.android.camera.CameraLauncher t46 f}
05-31 18:20:04.720  1037  2529 D WindowManager: relayoutVisibleWindow: Window{f2a2836 u0 com.android.launcher3/com.android.launcher3.Launcher EXITING} mAnimatingExit=true, mRemoveOnExit=false, mDestroying=false
05-31 18:20:04.739   706   706 I RQBalance-PowerHAL-Hints: Setting balanced mode
```

**Comment by MartinX3** [comment]
GCAM needs GAPPS.
